# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://krazedkrish.com
title: krazedkrish
email: krazedkrish@gmail.com
author: Shalil Awaley
description: "I am Shalil Awaley aka krazedkrish and tech. aficionado. I am a linux fan and absolutely love Emacs. I am into machine learning and data science." 
keywords: "linux-expert-linux ruby-developer-ruby on rails-krazedkrish krazedkrish-nepal available-for-hire-sydney available-for-hire-ruby available-for-hire-rails available-for-hire-python available-for-hire-devops available-for-hire-freelance available-for-hire-data-scientist available-for-hire-machine-learning"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/krazedkrish
  - title: github
    url: https://github.com/krazedkrish
  - title: linkedin
    url: https://np.linkedin.com/pub/shalil-awaley/69/618/b21
  - title: stack-overflow
    url: https://stackoverflow.com/users/5688098/krazedkrish

gems: [jekyll-sitemap]
