# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://krazedkrish.com
title: krazedkrish
email: krazedkrish@gmail.com
author: Shalil Awaley
description: "I am Shalil Awaley aka krazedkrish. I am a tech aficionado. I absolutely love Emacs and I am a linux fan. I can help you with software solutions to complex problems." 
keywords: "linux-expert-linux ruby-developer-ruby on rails-krazedkrish krazedkrish-nepal"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/krazedkrish
  - title: github
    url: https://github.com/krazedkrish
  - title: linkedin
    url: https://np.linkedin.com/pub/shalil-awaley/69/618/b21
